//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lux.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LuxParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILuxListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] LuxParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] LuxParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LuxParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LuxParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStat([NotNull] LuxParser.EmptyStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStat([NotNull] LuxParser.EmptyStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignStat([NotNull] LuxParser.AssignStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignStat([NotNull] LuxParser.AssignStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionCallStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallStat([NotNull] LuxParser.FunctionCallStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionCallStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallStat([NotNull] LuxParser.FunctionCallStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IncDecStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncDecStat_([NotNull] LuxParser.IncDecStat_Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IncDecStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncDecStat_([NotNull] LuxParser.IncDecStat_Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LabelStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelStat([NotNull] LuxParser.LabelStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LabelStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelStat([NotNull] LuxParser.LabelStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStat([NotNull] LuxParser.BreakStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStat([NotNull] LuxParser.BreakStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GotoStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoStat([NotNull] LuxParser.GotoStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GotoStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoStat([NotNull] LuxParser.GotoStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoStat([NotNull] LuxParser.DoStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoStat([NotNull] LuxParser.DoStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>WhileStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStat([NotNull] LuxParser.WhileStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>WhileStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStat([NotNull] LuxParser.WhileStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RepeatStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatStat([NotNull] LuxParser.RepeatStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RepeatStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatStat([NotNull] LuxParser.RepeatStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IfStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStat_([NotNull] LuxParser.IfStat_Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IfStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStat_([NotNull] LuxParser.IfStat_Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NumericForStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericForStat([NotNull] LuxParser.NumericForStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NumericForStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericForStat([NotNull] LuxParser.NumericForStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GenericForStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericForStat([NotNull] LuxParser.GenericForStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GenericForStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericForStat([NotNull] LuxParser.GenericForStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclStat([NotNull] LuxParser.FunctionDeclStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclStat([NotNull] LuxParser.FunctionDeclStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LocalFunctionDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalFunctionDeclStat([NotNull] LuxParser.LocalFunctionDeclStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LocalFunctionDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalFunctionDeclStat([NotNull] LuxParser.LocalFunctionDeclStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LocalDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalDeclStat([NotNull] LuxParser.LocalDeclStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LocalDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalDeclStat([NotNull] LuxParser.LocalDeclStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EnumDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclStat([NotNull] LuxParser.EnumDeclStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EnumDeclStat</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclStat([NotNull] LuxParser.EnumDeclStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ImportStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStat_([NotNull] LuxParser.ImportStat_Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ImportStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStat_([NotNull] LuxParser.ImportStat_Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExportStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExportStat_([NotNull] LuxParser.ExportStat_Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExportStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExportStat_([NotNull] LuxParser.ExportStat_Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclareStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareStat_([NotNull] LuxParser.DeclareStat_Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclareStat_</c>
	/// labeled alternative in <see cref="LuxParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareStat_([NotNull] LuxParser.DeclareStat_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.doBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoBlock([NotNull] LuxParser.DoBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.doBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoBlock([NotNull] LuxParser.DoBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] LuxParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] LuxParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.repeatLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatLoop([NotNull] LuxParser.RepeatLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.repeatLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatLoop([NotNull] LuxParser.RepeatLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStat([NotNull] LuxParser.IfStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.ifStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStat([NotNull] LuxParser.IfStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.elseIfClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfClause([NotNull] LuxParser.ElseIfClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.elseIfClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfClause([NotNull] LuxParser.ElseIfClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseClause([NotNull] LuxParser.ElseClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.elseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseClause([NotNull] LuxParser.ElseClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.numericFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericFor([NotNull] LuxParser.NumericForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.numericFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericFor([NotNull] LuxParser.NumericForContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.genericFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericFor([NotNull] LuxParser.GenericForContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.genericFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericFor([NotNull] LuxParser.GenericForContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] LuxParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] LuxParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostIncStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostIncStat([NotNull] LuxParser.PostIncStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostIncStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostIncStat([NotNull] LuxParser.PostIncStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostDecStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostDecStat([NotNull] LuxParser.PostDecStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostDecStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostDecStat([NotNull] LuxParser.PostDecStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PreIncStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreIncStat([NotNull] LuxParser.PreIncStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PreIncStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreIncStat([NotNull] LuxParser.PreIncStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PreDecStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreDecStat([NotNull] LuxParser.PreDecStatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PreDecStat</c>
	/// labeled alternative in <see cref="LuxParser.incDecStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreDecStat([NotNull] LuxParser.PreDecStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.returnStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStat([NotNull] LuxParser.ReturnStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.returnStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStat([NotNull] LuxParser.ReturnStatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDecl([NotNull] LuxParser.FunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDecl([NotNull] LuxParser.FunctionDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.localFunctionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalFunctionDecl([NotNull] LuxParser.LocalFunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.localFunctionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalFunctionDecl([NotNull] LuxParser.LocalFunctionDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.localDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalDecl([NotNull] LuxParser.LocalDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.localDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalDecl([NotNull] LuxParser.LocalDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ImportFrom</c>
	/// labeled alternative in <see cref="LuxParser.importStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportFrom([NotNull] LuxParser.ImportFromContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ImportFrom</c>
	/// labeled alternative in <see cref="LuxParser.importStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportFrom([NotNull] LuxParser.ImportFromContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ImportSideEffect</c>
	/// labeled alternative in <see cref="LuxParser.importStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportSideEffect([NotNull] LuxParser.ImportSideEffectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ImportSideEffect</c>
	/// labeled alternative in <see cref="LuxParser.importStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportSideEffect([NotNull] LuxParser.ImportSideEffectContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NamedImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedImport([NotNull] LuxParser.NamedImportContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedImport([NotNull] LuxParser.NamedImportContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DefaultImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultImport([NotNull] LuxParser.DefaultImportContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DefaultImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultImport([NotNull] LuxParser.DefaultImportContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NamespaceImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceImport([NotNull] LuxParser.NamespaceImportContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamespaceImport</c>
	/// labeled alternative in <see cref="LuxParser.importBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceImport([NotNull] LuxParser.NamespaceImportContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.importName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportName([NotNull] LuxParser.ImportNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.importName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportName([NotNull] LuxParser.ImportNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDecl([NotNull] LuxParser.EnumDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDecl([NotNull] LuxParser.EnumDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.enumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumMember([NotNull] LuxParser.EnumMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.enumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumMember([NotNull] LuxParser.EnumMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExportFunction</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExportFunction([NotNull] LuxParser.ExportFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExportFunction</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExportFunction([NotNull] LuxParser.ExportFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExportLocalFunction</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExportLocalFunction([NotNull] LuxParser.ExportLocalFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExportLocalFunction</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExportLocalFunction([NotNull] LuxParser.ExportLocalFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExportLocal</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExportLocal([NotNull] LuxParser.ExportLocalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExportLocal</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExportLocal([NotNull] LuxParser.ExportLocalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExportEnum</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExportEnum([NotNull] LuxParser.ExportEnumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExportEnum</c>
	/// labeled alternative in <see cref="LuxParser.exportStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExportEnum([NotNull] LuxParser.ExportEnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.declareStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareStat([NotNull] LuxParser.DeclareStatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.declareStat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareStat([NotNull] LuxParser.DeclareStatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclareFunction</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareFunction([NotNull] LuxParser.DeclareFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclareFunction</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareFunction([NotNull] LuxParser.DeclareFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclareVariable</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareVariable([NotNull] LuxParser.DeclareVariableContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclareVariable</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareVariable([NotNull] LuxParser.DeclareVariableContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclareModule</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareModule([NotNull] LuxParser.DeclareModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclareModule</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareModule([NotNull] LuxParser.DeclareModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DeclareEnum</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareEnum([NotNull] LuxParser.DeclareEnumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DeclareEnum</c>
	/// labeled alternative in <see cref="LuxParser.declareBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareEnum([NotNull] LuxParser.DeclareEnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.funcSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncSignature([NotNull] LuxParser.FuncSignatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.funcSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncSignature([NotNull] LuxParser.FuncSignatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.declareModuleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareModuleBlock([NotNull] LuxParser.DeclareModuleBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.declareModuleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareModuleBlock([NotNull] LuxParser.DeclareModuleBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.declareEnumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareEnumMember([NotNull] LuxParser.DeclareEnumMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.declareEnumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareEnumMember([NotNull] LuxParser.DeclareEnumMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ModuleDeclareFunction</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleDeclareFunction([NotNull] LuxParser.ModuleDeclareFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ModuleDeclareFunction</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleDeclareFunction([NotNull] LuxParser.ModuleDeclareFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ModuleDeclareVariable</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleDeclareVariable([NotNull] LuxParser.ModuleDeclareVariableContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ModuleDeclareVariable</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleDeclareVariable([NotNull] LuxParser.ModuleDeclareVariableContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ModuleDeclareEnum</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleDeclareEnum([NotNull] LuxParser.ModuleDeclareEnumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ModuleDeclareEnum</c>
	/// labeled alternative in <see cref="LuxParser.declareModuleMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleDeclareEnum([NotNull] LuxParser.ModuleDeclareEnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncName([NotNull] LuxParser.FuncNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncName([NotNull] LuxParser.FuncNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.funcBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncBody([NotNull] LuxParser.FuncBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.funcBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncBody([NotNull] LuxParser.FuncBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParamListWithNames</c>
	/// labeled alternative in <see cref="LuxParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamListWithNames([NotNull] LuxParser.ParamListWithNamesContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParamListWithNames</c>
	/// labeled alternative in <see cref="LuxParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamListWithNames([NotNull] LuxParser.ParamListWithNamesContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParamListVararg</c>
	/// labeled alternative in <see cref="LuxParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamListVararg([NotNull] LuxParser.ParamListVarargContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParamListVararg</c>
	/// labeled alternative in <see cref="LuxParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamListVararg([NotNull] LuxParser.ParamListVarargContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] LuxParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] LuxParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.varargParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarargParam([NotNull] LuxParser.VarargParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.varargParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarargParam([NotNull] LuxParser.VarargParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.varList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarList([NotNull] LuxParser.VarListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.varList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarList([NotNull] LuxParser.VarListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.nameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameList([NotNull] LuxParser.NameListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.nameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameList([NotNull] LuxParser.NameListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.attribNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribNameList([NotNull] LuxParser.AttribNameListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.attribNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribNameList([NotNull] LuxParser.AttribNameListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.attribName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribName([NotNull] LuxParser.AttribNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.attribName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribName([NotNull] LuxParser.AttribNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.attrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrib([NotNull] LuxParser.AttribContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.attrib"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrib([NotNull] LuxParser.AttribContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] LuxParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] LuxParser.ExprListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.typeAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeAnnotation([NotNull] LuxParser.TypeAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.typeAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeAnnotation([NotNull] LuxParser.TypeAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnionType</c>
	/// labeled alternative in <see cref="LuxParser.typeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionType([NotNull] LuxParser.UnionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnionType</c>
	/// labeled alternative in <see cref="LuxParser.typeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionType([NotNull] LuxParser.UnionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostfixType</c>
	/// labeled alternative in <see cref="LuxParser.typeSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixType([NotNull] LuxParser.PostfixTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostfixType</c>
	/// labeled alternative in <see cref="LuxParser.typeSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixType([NotNull] LuxParser.PostfixTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArraySuffix</c>
	/// labeled alternative in <see cref="LuxParser.typeSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArraySuffix([NotNull] LuxParser.ArraySuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArraySuffix</c>
	/// labeled alternative in <see cref="LuxParser.typeSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArraySuffix([NotNull] LuxParser.ArraySuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NullableSuffix</c>
	/// labeled alternative in <see cref="LuxParser.typeSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullableSuffix([NotNull] LuxParser.NullableSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NullableSuffix</c>
	/// labeled alternative in <see cref="LuxParser.typeSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullableSuffix([NotNull] LuxParser.NullableSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NilType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNilType([NotNull] LuxParser.NilTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NilType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNilType([NotNull] LuxParser.NilTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedType([NotNull] LuxParser.NamedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NamedType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedType([NotNull] LuxParser.NamedTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FuncType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncType([NotNull] LuxParser.FuncTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FuncType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncType([NotNull] LuxParser.FuncTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TableType_</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableType_([NotNull] LuxParser.TableType_Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TableType_</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableType_([NotNull] LuxParser.TableType_Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GroupedOrTupleType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupedOrTupleType([NotNull] LuxParser.GroupedOrTupleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GroupedOrTupleType</c>
	/// labeled alternative in <see cref="LuxParser.typeAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupedOrTupleType([NotNull] LuxParser.GroupedOrTupleTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionType([NotNull] LuxParser.FunctionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionType([NotNull] LuxParser.FunctionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeList([NotNull] LuxParser.TypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeList([NotNull] LuxParser.TypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyTableType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyTableType([NotNull] LuxParser.EmptyTableTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyTableType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyTableType([NotNull] LuxParser.EmptyTableTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapType([NotNull] LuxParser.MapTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MapType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapType([NotNull] LuxParser.MapTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructType([NotNull] LuxParser.StructTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructType</c>
	/// labeled alternative in <see cref="LuxParser.tableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructType([NotNull] LuxParser.StructTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructField([NotNull] LuxParser.StructFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructField([NotNull] LuxParser.StructFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PreIncExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreIncExpr([NotNull] LuxParser.PreIncExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PreIncExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreIncExpr([NotNull] LuxParser.PreIncExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BitwiseOrExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseOrExpr([NotNull] LuxParser.BitwiseOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BitwiseOrExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseOrExpr([NotNull] LuxParser.BitwiseOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ComparisonExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonExpr([NotNull] LuxParser.ComparisonExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ComparisonExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonExpr([NotNull] LuxParser.ComparisonExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeCheckExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeCheckExpr([NotNull] LuxParser.TypeCheckExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeCheckExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeCheckExpr([NotNull] LuxParser.TypeCheckExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionDefExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefExpr([NotNull] LuxParser.FunctionDefExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionDefExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefExpr([NotNull] LuxParser.FunctionDefExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PreDecExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreDecExpr([NotNull] LuxParser.PreDecExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PreDecExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreDecExpr([NotNull] LuxParser.PreDecExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalAndExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpr([NotNull] LuxParser.LogicalAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalAndExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpr([NotNull] LuxParser.LogicalAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NonNilAssertExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonNilAssertExpr([NotNull] LuxParser.NonNilAssertExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NonNilAssertExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonNilAssertExpr([NotNull] LuxParser.NonNilAssertExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FalseLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFalseLiteral([NotNull] LuxParser.FalseLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FalseLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFalseLiteral([NotNull] LuxParser.FalseLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiplicativeExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpr([NotNull] LuxParser.MultiplicativeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiplicativeExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpr([NotNull] LuxParser.MultiplicativeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TrueLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrueLiteral([NotNull] LuxParser.TrueLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TrueLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrueLiteral([NotNull] LuxParser.TrueLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostIncExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostIncExpr([NotNull] LuxParser.PostIncExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostIncExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostIncExpr([NotNull] LuxParser.PostIncExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NilCoalesceExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNilCoalesceExpr([NotNull] LuxParser.NilCoalesceExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NilCoalesceExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNilCoalesceExpr([NotNull] LuxParser.NilCoalesceExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostDecExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostDecExpr([NotNull] LuxParser.PostDecExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostDecExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostDecExpr([NotNull] LuxParser.PostDecExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BitShiftExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitShiftExpr([NotNull] LuxParser.BitShiftExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BitShiftExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitShiftExpr([NotNull] LuxParser.BitShiftExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BitwiseAndExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseAndExpr([NotNull] LuxParser.BitwiseAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BitwiseAndExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseAndExpr([NotNull] LuxParser.BitwiseAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] LuxParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] LuxParser.UnaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrefixExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixExpr([NotNull] LuxParser.PrefixExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrefixExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixExpr([NotNull] LuxParser.PrefixExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowerExpr([NotNull] LuxParser.PowerExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowerExpr([NotNull] LuxParser.PowerExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ConcatExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcatExpr([NotNull] LuxParser.ConcatExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ConcatExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcatExpr([NotNull] LuxParser.ConcatExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalOrExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpr([NotNull] LuxParser.LogicalOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalOrExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpr([NotNull] LuxParser.LogicalOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] LuxParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] LuxParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AdditiveExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpr([NotNull] LuxParser.AdditiveExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AdditiveExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpr([NotNull] LuxParser.AdditiveExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarargExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarargExpr([NotNull] LuxParser.VarargExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarargExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarargExpr([NotNull] LuxParser.VarargExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NilLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNilLiteral([NotNull] LuxParser.NilLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NilLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNilLiteral([NotNull] LuxParser.NilLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BitwiseXorExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseXorExpr([NotNull] LuxParser.BitwiseXorExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BitwiseXorExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseXorExpr([NotNull] LuxParser.BitwiseXorExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberLiteral([NotNull] LuxParser.NumberLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberLiteral</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberLiteral([NotNull] LuxParser.NumberLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeCastExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeCastExpr([NotNull] LuxParser.TypeCastExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeCastExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeCastExpr([NotNull] LuxParser.TypeCastExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TableConstructorExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableConstructorExpr([NotNull] LuxParser.TableConstructorExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TableConstructorExpr</c>
	/// labeled alternative in <see cref="LuxParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableConstructorExpr([NotNull] LuxParser.TableConstructorExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LtOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLtOp([NotNull] LuxParser.LtOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LtOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLtOp([NotNull] LuxParser.LtOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GtOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGtOp([NotNull] LuxParser.GtOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GtOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGtOp([NotNull] LuxParser.GtOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LteOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLteOp([NotNull] LuxParser.LteOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LteOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLteOp([NotNull] LuxParser.LteOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GteOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGteOp([NotNull] LuxParser.GteOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GteOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGteOp([NotNull] LuxParser.GteOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NeqOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNeqOp([NotNull] LuxParser.NeqOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NeqOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNeqOp([NotNull] LuxParser.NeqOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EqOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqOp([NotNull] LuxParser.EqOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EqOp</c>
	/// labeled alternative in <see cref="LuxParser.compareOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqOp([NotNull] LuxParser.EqOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LshiftOp</c>
	/// labeled alternative in <see cref="LuxParser.shiftOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLshiftOp([NotNull] LuxParser.LshiftOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LshiftOp</c>
	/// labeled alternative in <see cref="LuxParser.shiftOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLshiftOp([NotNull] LuxParser.LshiftOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RshiftOp</c>
	/// labeled alternative in <see cref="LuxParser.shiftOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRshiftOp([NotNull] LuxParser.RshiftOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RshiftOp</c>
	/// labeled alternative in <see cref="LuxParser.shiftOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRshiftOp([NotNull] LuxParser.RshiftOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddOp</c>
	/// labeled alternative in <see cref="LuxParser.additiveOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddOp([NotNull] LuxParser.AddOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddOp</c>
	/// labeled alternative in <see cref="LuxParser.additiveOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddOp([NotNull] LuxParser.AddOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SubOp</c>
	/// labeled alternative in <see cref="LuxParser.additiveOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubOp([NotNull] LuxParser.SubOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SubOp</c>
	/// labeled alternative in <see cref="LuxParser.additiveOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubOp([NotNull] LuxParser.SubOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulOp([NotNull] LuxParser.MulOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulOp([NotNull] LuxParser.MulOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DivOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivOp([NotNull] LuxParser.DivOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DivOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivOp([NotNull] LuxParser.DivOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FloorDivOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloorDivOp([NotNull] LuxParser.FloorDivOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FloorDivOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloorDivOp([NotNull] LuxParser.FloorDivOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ModOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModOp([NotNull] LuxParser.ModOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ModOp</c>
	/// labeled alternative in <see cref="LuxParser.multiplicativeOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModOp([NotNull] LuxParser.ModOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalNotOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalNotOp([NotNull] LuxParser.LogicalNotOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalNotOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalNotOp([NotNull] LuxParser.LogicalNotOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LengthOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLengthOp([NotNull] LuxParser.LengthOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LengthOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLengthOp([NotNull] LuxParser.LengthOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NegateOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegateOp([NotNull] LuxParser.NegateOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NegateOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegateOp([NotNull] LuxParser.NegateOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BitwiseNotOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseNotOp([NotNull] LuxParser.BitwiseNotOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BitwiseNotOp</c>
	/// labeled alternative in <see cref="LuxParser.unaryOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseNotOp([NotNull] LuxParser.BitwiseNotOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.prefixExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixExp([NotNull] LuxParser.PrefixExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.prefixExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixExp([NotNull] LuxParser.PrefixExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NameVarOrExp</c>
	/// labeled alternative in <see cref="LuxParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameVarOrExp([NotNull] LuxParser.NameVarOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NameVarOrExp</c>
	/// labeled alternative in <see cref="LuxParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameVarOrExp([NotNull] LuxParser.NameVarOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenVarOrExp</c>
	/// labeled alternative in <see cref="LuxParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenVarOrExp([NotNull] LuxParser.ParenVarOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenVarOrExp</c>
	/// labeled alternative in <see cref="LuxParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenVarOrExp([NotNull] LuxParser.ParenVarOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DotSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotSuffix([NotNull] LuxParser.DotSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DotSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotSuffix([NotNull] LuxParser.DotSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OptDotSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptDotSuffix([NotNull] LuxParser.OptDotSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OptDotSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptDotSuffix([NotNull] LuxParser.OptDotSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IndexSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexSuffix([NotNull] LuxParser.IndexSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IndexSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexSuffix([NotNull] LuxParser.IndexSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodCallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCallSuffix([NotNull] LuxParser.MethodCallSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodCallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCallSuffix([NotNull] LuxParser.MethodCallSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallSuffix([NotNull] LuxParser.CallSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallSuffix([NotNull] LuxParser.CallSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OptCallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptCallSuffix([NotNull] LuxParser.OptCallSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OptCallSuffix</c>
	/// labeled alternative in <see cref="LuxParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptCallSuffix([NotNull] LuxParser.OptCallSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NameVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameVar([NotNull] LuxParser.NameVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NameVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameVar([NotNull] LuxParser.NameVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FieldVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldVar([NotNull] LuxParser.FieldVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FieldVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldVar([NotNull] LuxParser.FieldVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IndexVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexVar([NotNull] LuxParser.IndexVarContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IndexVar</c>
	/// labeled alternative in <see cref="LuxParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexVar([NotNull] LuxParser.IndexVarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DirectCall</c>
	/// labeled alternative in <see cref="LuxParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectCall([NotNull] LuxParser.DirectCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DirectCall</c>
	/// labeled alternative in <see cref="LuxParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectCall([NotNull] LuxParser.DirectCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodCall</c>
	/// labeled alternative in <see cref="LuxParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCall([NotNull] LuxParser.MethodCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodCall</c>
	/// labeled alternative in <see cref="LuxParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCall([NotNull] LuxParser.MethodCallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenArgs([NotNull] LuxParser.ParenArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenArgs([NotNull] LuxParser.ParenArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TableArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableArgs([NotNull] LuxParser.TableArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TableArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableArgs([NotNull] LuxParser.TableArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StringArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringArgs([NotNull] LuxParser.StringArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StringArgs</c>
	/// labeled alternative in <see cref="LuxParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringArgs([NotNull] LuxParser.StringArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDef([NotNull] LuxParser.FunctionDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.functionDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDef([NotNull] LuxParser.FunctionDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.tableConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableConstructor([NotNull] LuxParser.TableConstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.tableConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableConstructor([NotNull] LuxParser.TableConstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.fieldList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldList([NotNull] LuxParser.FieldListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.fieldList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldList([NotNull] LuxParser.FieldListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BracketField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracketField([NotNull] LuxParser.BracketFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BracketField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracketField([NotNull] LuxParser.BracketFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NameField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameField([NotNull] LuxParser.NameFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NameField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameField([NotNull] LuxParser.NameFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ValueField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueField([NotNull] LuxParser.ValueFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ValueField</c>
	/// labeled alternative in <see cref="LuxParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueField([NotNull] LuxParser.ValueFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuxParser.fieldSep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldSep([NotNull] LuxParser.FieldSepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuxParser.fieldSep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldSep([NotNull] LuxParser.FieldSepContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IntLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntLit([NotNull] LuxParser.IntLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IntLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntLit([NotNull] LuxParser.IntLitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>HexLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexLit([NotNull] LuxParser.HexLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>HexLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexLit([NotNull] LuxParser.HexLitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FloatLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatLit([NotNull] LuxParser.FloatLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FloatLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatLit([NotNull] LuxParser.FloatLitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>HexFloatLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexFloatLit([NotNull] LuxParser.HexFloatLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>HexFloatLit</c>
	/// labeled alternative in <see cref="LuxParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexFloatLit([NotNull] LuxParser.HexFloatLitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleQuotedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleQuotedStr([NotNull] LuxParser.DoubleQuotedStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleQuotedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleQuotedStr([NotNull] LuxParser.DoubleQuotedStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleQuotedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleQuotedStr([NotNull] LuxParser.SingleQuotedStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleQuotedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleQuotedStr([NotNull] LuxParser.SingleQuotedStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LongStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLongStr([NotNull] LuxParser.LongStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LongStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLongStr([NotNull] LuxParser.LongStrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InterpolatedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterpolatedStr([NotNull] LuxParser.InterpolatedStrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InterpolatedStr</c>
	/// labeled alternative in <see cref="LuxParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterpolatedStr([NotNull] LuxParser.InterpolatedStrContext context);
}
